@ECHO OFF
set ADVISOR_2020_DIR=c:\program files ^(x86^)\intelswtools\advisor 2020\
set ADVISOR_2022_DIR=c:\program files ^(x86^)\intel\oneapi\advisor\2022.0.0
set ALLUSERSPROFILE=c:\programdata
set APPDATA=c:\users\indrekis\appdata\roaming
set CARBON_MEM_DISABLE=1
set CLASSPATH=.;c:\program files ^(x86^)\java\jre1.8.0_151\lib\ext\qtjava.zip
set COMMANDER_DRIVE=d:
set COMMANDER_EXE=d:\totalcmd3\totalcmd64.exe
set COMMANDER_INI=d:\totalcmd3\wincmd.ini
set COMMANDER_INSTANCE=1
set COMMANDER_PATH=d:\totalcmd3
set commandprompttype=native
set CommonProgramFiles=c:\program files\common files
set CommonProgramFiles(x86)=c:\program files ^(x86^)\common files
set CommonProgramW6432=c:\program files\common files
set COMPUTERNAME=desktop-21utcdt
set ComSpec=c:\windows\system32\cmd.exe
set CUDA_PATH_V10_2=c:\program files\nvidia gpu computing toolkit\cuda\v10.2
set devenvdir=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\
set DOTNET_MSBUILD_SDK_RESOLVER_SDKS_DIR=c:\program files ^(x86^)\pvs-studio\buildtools\sdks
set DriverData=c:\windows\system32\drivers\driverdata
set extensionsdkdir=c:\program files ^(x86^)\microsoft sdks\windows kits\10\extensionsdks
set FPS_BROWSER_APP_PROFILE_STRING=internet explorer
set FPS_BROWSER_USER_PROFILE_STRING=default
set framework40version=v4.0
set frameworkdir=c:\windows\microsoft.net\framework64\
set frameworkdir64=c:\windows\microsoft.net\framework64\
set frameworkversion=v4.0.30319
set frameworkversion64=v4.0.30319
set HOMEDRIVE=c:
set HOMEPATH=\users\indrekis
set htmlhelpdir=c:\program files ^(x86^)\html help workshop
set ICPP_COMPILER20=c:\program files ^(x86^)\intelswtools\compilers_and_libraries_2020.4.311\windows\
set ifcpath=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\ifc\x64
set include=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\include;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\include;c:\program files ^(x86^)\windows kits\netfxsdk\4.6.1\include\um;c:\program files ^(x86^)\windows kits\10\include\10.0.22000.0\ucrt;c:\program files ^(x86^)\windows kits\10\include\10.0.22000.0\shared;c:\program files ^(x86^)\windows kits\10\include\10.0.22000.0\um;c:\program files ^(x86^)\windows kits\10\include\10.0.22000.0\winrt;c:\program files ^(x86^)\windows kits\10\include\10.0.22000.0\cppwinrt
set INSPECTOR_2020_DIR=c:\program files ^(x86^)\intelswtools\inspector 2020\
set INSPECTOR_2022_DIR=c:\program files ^(x86^)\intel\oneapi\inspector\2022.0.0
set INTELOCLPATH=c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x86
set INTELOCLSDKROOT=c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\
set INTEL_DEV_REDIST=c:\program files ^(x86^)\common files\intel\shared libraries\
set INTEL_LICENSE_FILE=c:\program files ^(x86^)\common files\intel\licenses
set IVIROOTDIR32=c:\program files ^(x86^)\ivi foundation\ivi\
set IVIROOTDIR64=c:\program files\ivi foundation\ivi\
set I_MPI_ONEAPI_ROOT=c:\program files ^(x86^)\intel\oneapi\mpi\2021.5.1
set I_MPI_ROOT=c:\program files ^(x86^)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi
set JAVA_HOME=c:\program files ^(x86^)\java\jre1.8.0_231
set KMP_DUPLICATE_LIB_OK=true
set lib=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x64;c:\program files ^(x86^)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files ^(x86^)\windows kits\10\lib\10.0.22000.0\ucrt\x64;c:\program files ^(x86^)\windows kits\10\lib\10.0.22000.0\um\x64
set libpath=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x86\store\references;c:\program files ^(x86^)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files ^(x86^)\windows kits\10\references\10.0.22000.0;c:\windows\microsoft.net\framework64\v4.0.30319
set LOCALAPPDATA=c:\users\indrekis\appdata\local
set LOGONSERVER=\\desktop-21utcdt
set MIC_LD_LIBRARY_PATH=c:\program files ^(x86^)\common files\intel\shared libraries\compiler\lib\intel64_win_mic
set MOZ_PLUGIN_PATH=c:\program files ^(x86^)\foxit software\foxit reader\plugins\
set MSBuildLoadMicrosoftTargetsReadOnly=true
set MSBUILD_EXE_PATH=c:\program files ^(x86^)\pvs-studio\buildtools\msbuild.exe
set MSMPI_BENCHMARKS=c:\program files\microsoft mpi\benchmarks\
set MSMPI_BIN=c:\program files\microsoft mpi\bin\
set netfxsdkdir=c:\program files ^(x86^)\windows kits\netfxsdk\4.6.1\
set NO_XILINX_DATA_LICENSE=hidden
set NUMBER_OF_PROCESSORS=8
set NVCUDASAMPLES10_2_ROOT=c:\programdata\nvidia corporation\cuda samples\v10.2
set NVTOOLSEXT_PATH=c:\program files\nvidia corporation\nvtoolsext\
set ONEAPI_ROOT=c:\program files ^(x86^)\intel\oneapi\
set OneDrive=c:\users\indrekis\onedrive
set OS=windows_nt
set Path=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files ^(x86^)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files ^(x86^)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files ^(x86^)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files ^(x86^)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\;c:\program files ^(x86^)\html help workshop;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools\devinit;c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\x64;c:\program files ^(x86^)\windows kits\10\bin\x64;c:\program files ^(x86^)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools\;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\x64;c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\x86;c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide;c:\program files ^(x86^)\html help workshop;c:\program files ^(x86^)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x86;c:\program files ^(x86^)\common files\intel\shared libraries\ia32;c:\program files ^(x86^)\common files\intel\shared libraries\intel64;c:\program files ^(x86^)\common files\intel\shared libraries\;c:\program files ^(x86^)\intel\oneapi\tbb\latest\redist\intel64\vc_mt\;c:\program files ^(x86^)\intel\oneapi\tbb\latest\redist\ia32\vc_mt\;c:\program files ^(x86^)\pc connectivity solution\;c:\program files\microsoft mpi\bin\;c:\program files ^(x86^)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi\intel64\bin;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\ia32_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\ia32_win\mpirt;c:\program files ^(x86^)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files ^(x86^)\nvidia corporation\physx\common;c:\program files ^(x86^)\winscp\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files ^(x86^)\quicktime\qtsystem\;c:\users\indrekis\.cargo\bin;c:\windows\system32\openssh\;c:\program files\nvidia corporation\nvidia nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\nvidia corporation\nsight compute 2019.5.0\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files ^(x86^)\the varcem team\varcem\\bin;c:\program files ^(x86^)\intel\intel^(r^) management engine components\dal;c:\program files\intel\intel^(r^) management engine components\dal;c:\program files\calibre2\;c:\program files\putty\;c:\program files\miktex\miktex\bin\x64\;c:\program files\dotnet\;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\gs\gs9.56.1\bin;c:\program files\git\cmd;c:\program files\pandoc\;c:\users\indrekis\appdata\local\programs\python\python310\scripts\;c:\users\indrekis\appdata\local\programs\python\python310\;d:\workcomp\msys2_64_2015\mingw64\bin;c:\users\indrekis\.cargo\bin;c:\users\indrekis\appdata\local\microsoft\windowsapps;c:\program files ^(x86^)\atmel\flip 3.4.7\bin;c:\opensourcefiles\radare2;d:\embedded\intelfpga_lite\19.1\modelsim_ase\win32aloem;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\indrekis\appdata\local\programs\ipfs desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win;c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\llvm\x64\bin;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja
set PATHEXT=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
set PkgDefApplicationConfigFile=c:\users\indrekis\appdata\local\microsoft\visualstudio\16.0_e1eaee60\devenv.exe.config
set platform=x64
set PROCESSOR_ARCHITECTURE=amd64
set PROCESSOR_IDENTIFIER=intel64 family 6 model 158 stepping 9, genuineintel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9e09
set ProgramData=c:\programdata
set ProgramFiles=c:\program files
set ProgramFiles(x86)=c:\program files ^(x86^)
set ProgramW6432=c:\program files
set PROMPT=$p$g
set PSModulePath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
set PUBLIC=c:\users\public
set PVSBuildTools_ExtensionsPath_Current=c:\program files ^(x86^)\microsoft visual studio\2019\community\msbuild
set PVSBuildTools_ExtensionsPath_VS2017=c:\program files ^(x86^)\msbuild\
set PVSBuildTools_ExtensionsPath_VS2019=c:\program files ^(x86^)\microsoft visual studio\2019\community\msbuild
set PVSBuildTools_ExtensionsPath_VS2022=c:\program files ^(x86^)\microsoft visual studio\2019\community\msbuild
set PVSBuildTools_InstallDir_Current=c:\program files ^(x86^)\microsoft visual studio\2019\community
set PVSBuildTools_InstallDir_VS2019=c:\program files ^(x86^)\microsoft visual studio\2019\community
set PVSBuildTools_InstallDir_VS2022=c:\program files\microsoft visual studio\2022\community
set PVSBuildTools_VCTargetsPath_Current=c:\program files ^(x86^)\microsoft visual studio\2019\community\msbuild\microsoft\vc\v160\
set PVSBuildTools_VisualStudioVersion_Current=16.0
set QSYS_ROOTDIR=d:\embedded\intelfpga_lite\19.1\quartus\sopc_builder\bin
set QTJAVA=c:\program files ^(x86^)\java\jre1.8.0_151\lib\ext\qtjava.zip
set QUARTUS_ROOTDIR=c:\program files ^(x86^)\intel\oneapi\intelfpgadpcpp\2021.1.1\quartusprimepro\19.4\quartus
set ServiceHubLogSessionKey=892d306d
set SESSIONNAME=console
set SOPC_KIT_NIOS2=c:\program files ^(x86^)\intel\oneapi\intelfpgadpcpp\2021.1.1\quartusprimepro\19.4\nios2eds
set str="D:\WorkWWW\Blog\ComputersHistory.S\System_soft\tcmp_fdimage_plugin\img_source\IMGwcx.cpp.PVS-Studio.preprocess.cmd"
set SystemDrive=c:
set SystemRoot=c:\windows
set TEMP=c:\users\indrekis\appdata\local\temp
set ThreadedWaitDialogDpiContext=-4
set TMP=c:\users\indrekis\appdata\local\temp
set ucrtversion=10.0.22000.0
set universalcrtsdkdir=c:\program files ^(x86^)\windows kits\10\
set USERDOMAIN=desktop-21utcdt
set USERDOMAIN_ROAMINGPROFILE=desktop-21utcdt
set USERNAME=indrekis
set USERPROFILE=c:\users\indrekis
set VBOX_MSI_INSTALL_PATH=c:\program files\oracle\virtualbox\
set vcideinstalldir=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\vc\
set vcinstalldir=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\
set vctoolsinstalldir=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\
set vctoolsredistdir=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\redist\msvc\14.29.30133\
set vctoolsversion=14.29.30133
set VisualStudioDir=c:\users\indrekis\documents\visual studio 2019
set VisualStudioEdition=microsoft visual studio community 2019
set VisualStudioVersion=16.0
set VS110COMNTOOLS=c:\program files ^(x86^)\microsoft visual studio 11.0\common7\tools\
set VS140COMNTOOLS=c:\program files ^(x86^)\microsoft visual studio 14.0\common7\tools\
set vs160comntools=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools\
set VS2017INSTALLDIR=c:\program files ^(x86^)\microsoft visual studio\2017\community
set VS2019INSTALLDIR=c:\program files ^(x86^)\microsoft visual studio\2019\community
set VSAPPIDDIR=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide\
set VSAPPIDNAME=devenv.exe
set vscmd_arg_app_plat=desktop
set vscmd_arg_host_arch=x64
set vscmd_arg_tgt_arch=x64
set vscmd_ver=16.11.16
set vsinstalldir=c:\program files ^(x86^)\microsoft visual studio\2019\community\
set VSLANG=1033
set VSSKUEDITION=community
set VTUNE_PROFILER_2020_DIR=c:\program files ^(x86^)\intelswtools\vtune profiler 2020\
set VTUNE_PROFILER_2022_DIR=c:\program files ^(x86^)\intel\oneapi\vtune\2022.0.0
set VXIPNPPATH=c:\program files ^(x86^)\ivi foundation\visa\
set VXIPNPPATH64=c:\program files\ivi foundation\visa\
set windir=c:\windows
set windowslibpath=c:\program files ^(x86^)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files ^(x86^)\windows kits\10\references\10.0.22000.0
set windowssdkbinpath=c:\program files ^(x86^)\windows kits\10\bin\
set windowssdkdir=c:\program files ^(x86^)\windows kits\10\
set windowssdklibversion=10.0.22000.0\
set windowssdkverbinpath=c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\
set windowssdkversion=10.0.22000.0\
set windowssdk_executablepath_x64=c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
set windowssdk_executablepath_x86=c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
set ZES_ENABLE_SYSMAN=1
set __devinit_path=c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools\devinit\devinit.exe
set __dotnet_add_64bit=1
set __dotnet_preferred_bitness=64
set __vscmd_preinit_path=c:\program files ^(x86^)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\x64;c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files ^(x86^)\windows kits\10\bin\10.0.22000.0\x86;c:\program files ^(x86^)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\tools;c:\program files ^(x86^)\microsoft visual studio\2019\community\common7\ide;c:\program files ^(x86^)\html help workshop;c:\program files ^(x86^)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files ^(x86^)\intelswtools\system_studio_2020\opencl\sdk\bin\x86;c:\program files ^(x86^)\common files\intel\shared libraries\ia32;c:\program files ^(x86^)\common files\intel\shared libraries\intel64;c:\program files ^(x86^)\common files\intel\shared libraries\;c:\program files ^(x86^)\intel\oneapi\tbb\latest\redist\intel64\vc_mt\;c:\program files ^(x86^)\intel\oneapi\tbb\latest\redist\ia32\vc_mt\;c:\program files ^(x86^)\pc connectivity solution\;c:\program files\microsoft mpi\bin\;c:\program files ^(x86^)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi\intel64\bin;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\ia32_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files ^(x86^)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files ^(x86^)\common files\intel\shared libraries\redist\ia32_win\mpirt;c:\program files ^(x86^)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files ^(x86^)\nvidia corporation\physx\common;c:\program files ^(x86^)\winscp\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files ^(x86^)\quicktime\qtsystem\;c:\users\indrekis\.cargo\bin;c:\windows\system32\openssh\;c:\program files\nvidia corporation\nvidia nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\nvidia corporation\nsight compute 2019.5.0\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files ^(x86^)\the varcem team\varcem\\bin;c:\program files ^(x86^)\intel\intel^(r^) management engine components\dal;c:\program files\intel\intel^(r^) management engine components\dal;c:\program files\calibre2\;c:\program files\putty\;c:\program files\miktex\miktex\bin\x64\;c:\program files\dotnet\;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\gs\gs9.56.1\bin;c:\program files\git\cmd;c:\program files\pandoc\;c:\users\indrekis\appdata\local\programs\python\python310\scripts\;c:\users\indrekis\appdata\local\programs\python\python310\;d:\workcomp\msys2_64_2015\mingw64\bin;c:\users\indrekis\.cargo\bin;c:\users\indrekis\appdata\local\microsoft\windowsapps;c:\program files ^(x86^)\atmel\flip 3.4.7\bin;c:\opensourcefiles\radare2;d:\embedded\intelfpga_lite\19.1\modelsim_ase\win32aloem;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\indrekis\appdata\local\programs\ipfs desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win
set __vscmd_script_err_count=0
@call "c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64\cl.exe" @"imgwcx1.cpp_CL_42496.CLMonitoring.bat.rsp" 2>&1
