@ECHO OFF
set ADVISOR_2020_DIR=C:\Program Files ^(x86^)\IntelSWTools\Advisor 2020\
set ADVISOR_2022_DIR=C:\Program Files ^(x86^)\Intel\oneAPI\advisor\2022.0.0
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\indrekis\AppData\Roaming
set CAExcludePath=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\include;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\ucrt;;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\um;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\shared;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\winrt;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\cppwinrt;C:\Program Files ^(x86^)\Windows Kits\NETFXSDK\4.6.1\Include\um;
set CARBON_MEM_DISABLE=1
set CLASSPATH=.;C:\Program Files ^(x86^)\Java\jre1.8.0_151\lib\ext\QTJava.zip
set COMMANDER_DRIVE=D:
set COMMANDER_EXE=D:\totalcmd3\TOTALCMD64.EXE
set COMMANDER_INI=D:\totalcmd3\wincmd.ini
set COMMANDER_INSTANCE=1
set COMMANDER_PATH=D:\totalcmd3
set CommonProgramFiles=C:\Program Files ^(x86^)\Common Files
set CommonProgramFiles(x86)=C:\Program Files ^(x86^)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-21UTCDT
set ComSpec=C:\WINDOWS\system32\cmd.exe
set CUDA_PATH_V10_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
set DriverData=C:\Windows\System32\Drivers\DriverData
set EXTERNAL_INCLUDE=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\include;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\include;;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\ucrt;;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\UnitTest\include;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\um;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\shared;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\winrt;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\cppwinrt;C:\Program Files ^(x86^)\Windows Kits\NETFXSDK\4.6.1\Include\um;;C:\WorkComp\vcpkg2022\vcpkg\installed\x64-windows\include
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set HOMEDRIVE=C:
set HOMEPATH=\Users\indrekis
set ICPP_COMPILER20=C:\Program Files ^(x86^)\IntelSWTools\compilers_and_libraries_2020.4.311\windows\
set INCLUDE=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\include;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\include;;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\ucrt;;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\UnitTest\include;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\um;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\shared;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\winrt;C:\Program Files ^(x86^)\Windows Kits\10\Include\10.0.22000.0\cppwinrt;C:\Program Files ^(x86^)\Windows Kits\NETFXSDK\4.6.1\Include\um;;C:\WorkComp\vcpkg2022\vcpkg\installed\x64-windows\include
set INSPECTOR_2020_DIR=C:\Program Files ^(x86^)\IntelSWTools\Inspector 2020\
set INSPECTOR_2022_DIR=C:\Program Files ^(x86^)\Intel\oneAPI\inspector\2022.0.0
set INTELOCLPATH=C:\Program Files ^(x86^)\IntelSWTools\system_studio_2020\OpenCL\sdk\bin\x64;C:\Program Files ^(x86^)\IntelSWTools\system_studio_2020\OpenCL\sdk\bin\x86
set INTELOCLSDKROOT=C:\Program Files ^(x86^)\IntelSWTools\system_studio_2020\OpenCL\sdk\
set INTEL_DEV_REDIST=C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\
set INTEL_LICENSE_FILE=C:\Program Files ^(x86^)\Common Files\Intel\Licenses
set IVIROOTDIR32=C:\Program Files ^(x86^)\IVI Foundation\IVI\
set IVIROOTDIR64=C:\Program Files\IVI Foundation\IVI\
set I_MPI_ONEAPI_ROOT=C:\Program Files ^(x86^)\Intel\oneAPI\mpi\2021.5.1
set I_MPI_ROOT=C:\Program Files ^(x86^)\IntelSWTools\compilers_and_libraries_2020.4.311\windows\mpi
set JAVA_HOME=c:\Program Files ^(x86^)\Java\jre1.8.0_231
set KMP_DUPLICATE_LIB_OK=TRUE
set LIB=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x64;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\lib\x64;;C:\Program Files ^(x86^)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\UnitTest\lib;C:\Program Files ^(x86^)\Windows Kits\10\lib\10.0.22000.0\um\x64;C:\Program Files ^(x86^)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;
set LIBPATH=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x64;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;
set LOCALAPPDATA=C:\Users\indrekis\AppData\Local
set LOGONSERVER=\\DESKTOP-21UTCDT
set MIC_LD_LIBRARY_PATH=C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
set MOZ_PLUGIN_PATH=C:\Program Files ^(x86^)\Foxit Software\Foxit Reader\plugins\
set MSBuildLoadMicrosoftTargetsReadOnly=true
set MSMPI_BENCHMARKS=C:\Program Files\Microsoft MPI\Benchmarks\
set MSMPI_BIN=C:\Program Files\Microsoft MPI\Bin\
set NO_XILINX_DATA_LICENSE=HIDDEN
set NUMBER_OF_PROCESSORS=8
set NVCUDASAMPLES10_2_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
set NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
set ONEAPI_ROOT=C:\Program Files ^(x86^)\Intel\oneAPI\
set OneDrive=C:\Users\indrekis\OneDrive
set OS=Windows_NT
set Path=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86;C:\Program Files ^(x86^)\Windows Kits\10\bin\10.0.22000.0\x86;;C:\Program Files ^(x86^)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\Common7\tools;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\Common7\ide;C:\Program Files ^(x86^)\HTML Help Workshop;;C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\;;C:\Program Files ^(x86^)\IntelSWTools\system_studio_2020\OpenCL\sdk\bin\x64;C:\Program Files ^(x86^)\IntelSWTools\system_studio_2020\OpenCL\sdk\bin\x86;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\ia32;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\intel64;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\;C:\Program Files ^(x86^)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt\;C:\Program Files ^(x86^)\Intel\oneAPI\tbb\latest\redist\ia32\vc_mt\;C:\Program Files ^(x86^)\PC Connectivity Solution\;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files ^(x86^)\IntelSWTools\compilers_and_libraries_2020.4.311\windows\mpi\intel64\bin;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files ^(x86^)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files ^(x86^)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files ^(x86^)\NVIDIA Corporation\PhysX\Common;C:\Program Files ^(x86^)\WinSCP\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files ^(x86^)\QuickTime\QTSystem\;c:\Users\indrekis\.cargo\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files ^(x86^)\The VARCem Team\VARCem\\bin;C:\Program Files ^(x86^)\Intel\Intel^(R^) Management Engine Components\DAL;C:\Program Files\Intel\Intel^(R^) Management Engine Components\DAL;C:\Program Files\Calibre2\;C:\Program Files\PuTTY\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\gs\gs9.56.1\bin;C:\Program Files\Git\cmd;C:\Program Files\Pandoc\;C:\Users\indrekis\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\indrekis\AppData\Local\Programs\Python\Python310\;d:\WorkComp\msys2_64_2015\mingw64\bin;C:\Users\indrekis\.cargo\bin;C:\Users\indrekis\AppData\Local\Microsoft\WindowsApps;C:\Program Files ^(x86^)\Atmel\Flip 3.4.7\bin;C:\OpenSourceFiles\radare2;;D:\Embedded\intelFPGA_lite\19.1\modelsim_ase\win32aloem;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\indrekis\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win;
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PkgDefApplicationConfigFile=C:\Users\indrekis\AppData\Local\Microsoft\VisualStudio\16.0_e1eaee60\devenv.exe.config
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9e09
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files ^(x86^)
set ProgramFiles(x86)=C:\Program Files ^(x86^)
set ProgramW6432=C:\Program Files
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set QSYS_ROOTDIR=D:\Embedded\intelFPGA_lite\19.1\quartus\sopc_builder\bin
set QTJAVA=C:\Program Files ^(x86^)\Java\jre1.8.0_151\lib\ext\QTJava.zip
set QUARTUS_ROOTDIR=C:\Program Files ^(x86^)\Intel\oneAPI\intelfpgadpcpp\2021.1.1\QuartusPrimePro\19.4\quartus
set ServiceHubLogSessionKey=892D306D
set SESSIONNAME=Console
set SOPC_KIT_NIOS2=C:\Program Files ^(x86^)\Intel\oneAPI\intelfpgadpcpp\2021.1.1\QuartusPrimePro\19.4\nios2eds
set SystemDrive=C:
set SystemRoot=C:\WINDOWS
set TEMP=C:\Users\indrekis\AppData\Local\Temp
set ThreadedWaitDialogDpiContext=-4
set TMP=C:\Users\indrekis\AppData\Local\Temp
set TRACKER_ENABLED=1
set TRACKER_INTERMEDIATE=D:\WorkWWW\Blog\ComputersHistory.S\System_soft\tcmp_fdimage_plugin\img_source\x64\Debug\IMGwcx.tlog
set TRACKER_OUTOFPROC=1
set TRACKER_RESPONSEFILE=C:\Users\indrekis\AppData\Local\Temp\tmp1954dd63ddf845178cee4efa9dd53f90.tmp
set TRACKER_ROOTFILES=
set TRACKER_TOOL=
set TRACKER_TOOLCHAIN=
set USERDOMAIN=DESKTOP-21UTCDT
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-21UTCDT
set USERNAME=indrekis
set USERPROFILE=C:\Users\indrekis
set VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
set VisualStudioDir=C:\Users\indrekis\Documents\Visual Studio 2019
set VisualStudioEdition=Microsoft Visual Studio Community 2019
set VisualStudioVersion=16.0
set VS110COMNTOOLS=C:\Program Files ^(x86^)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS140COMNTOOLS=C:\Program Files ^(x86^)\Microsoft Visual Studio 14.0\Common7\Tools\
set VS2017INSTALLDIR=C:\Program Files ^(x86^)\Microsoft Visual Studio\2017\Community
set VS2019INSTALLDIR=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community
set VSAPPIDDIR=C:\Program Files ^(x86^)\Microsoft Visual Studio\2019\Community\Common7\IDE\
set VSAPPIDNAME=devenv.exe
set VSLANG=1033
set VSSKUEDITION=Community
set VSTEL_CurrentSolutionBuildID=484887341
set VSTEL_ProjectID={1EDF664D-9C37-4752-A938-DE7CA10C9895}
set VSTEL_SolutionSessionID={9636BDDD-2CC4-455F-B722-CAE204024F1A}
set VTUNE_PROFILER_2020_DIR=C:\Program Files ^(x86^)\IntelSWTools\VTune Profiler 2020\
set VTUNE_PROFILER_2022_DIR=C:\Program Files ^(x86^)\Intel\oneAPI\vtune\2022.0.0
set VXIPNPPATH=C:\Program Files ^(x86^)\IVI Foundation\VISA\
set VXIPNPPATH64=C:\Program Files\IVI Foundation\VISA\
set windir=C:\WINDOWS
set ZES_ENABLE_SYSMAN=1
@call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\CL.exe" @"stdafx.cpp_CL_41204.CLMonitoring.bat.rsp" 2>&1
