@set advisor_2020_dir=c:\program files (x86)\intelswtools\advisor 2020\
@set advisor_2022_dir=c:\program files (x86)\intel\oneapi\advisor\2022.0.0
@set allusersprofile=c:\programdata
@set appdata=c:\users\indrekis\appdata\roaming
@set carbon_mem_disable=1
@set classpath=.;c:\program files (x86)\java\jre1.8.0_151\lib\ext\qtjava.zip
@set commander_drive=d:
@set commander_exe=d:\totalcmd3\totalcmd64.exe
@set commander_ini=d:\totalcmd3\wincmd.ini
@set commander_instance=1
@set commander_path=d:\totalcmd3
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-21utcdt
@set comspec=c:\windows\system32\cmd.exe
@set cuda_path_v10_2=c:\program files\nvidia gpu computing toolkit\cuda\v10.2
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\indrekis
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set icpp_compiler20=c:\program files (x86)\intelswtools\compilers_and_libraries_2020.4.311\windows\
@set ifcpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\ifc\x64
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.22000.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.22000.0\shared;c:\program files (x86)\windows kits\10\include\10.0.22000.0\um;c:\program files (x86)\windows kits\10\include\10.0.22000.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.22000.0\cppwinrt
@set inspector_2020_dir=c:\program files (x86)\intelswtools\inspector 2020\
@set inspector_2022_dir=c:\program files (x86)\intel\oneapi\inspector\2022.0.0
@set inteloclpath=c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x86
@set inteloclsdkroot=c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\
@set intel_dev_redist=c:\program files (x86)\common files\intel\shared libraries\
@set intel_license_file=c:\program files (x86)\common files\intel\licenses
@set ivirootdir32=c:\program files (x86)\ivi foundation\ivi\
@set ivirootdir64=c:\program files\ivi foundation\ivi\
@set i_mpi_oneapi_root=c:\program files (x86)\intel\oneapi\mpi\2021.5.1
@set i_mpi_root=c:\program files (x86)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi
@set java_home=c:\program files (x86)\java\jre1.8.0_231
@set kmp_duplicate_lib_ok=true
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.22000.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.22000.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files (x86)\windows kits\10\references\10.0.22000.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\indrekis\appdata\local
@set logonserver=\\desktop-21utcdt
@set mic_ld_library_path=c:\program files (x86)\common files\intel\shared libraries\compiler\lib\intel64_win_mic
@set moz_plugin_path=c:\program files (x86)\foxit software\foxit reader\plugins\
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set msmpi_benchmarks=c:\program files\microsoft mpi\benchmarks\
@set msmpi_bin=c:\program files\microsoft mpi\bin\
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set no_xilinx_data_license=hidden
@set number_of_processors=8
@set nvcudasamples10_2_root=c:\programdata\nvidia corporation\cuda samples\v10.2
@set nvtoolsext_path=c:\program files\nvidia corporation\nvtoolsext\
@set oneapi_root=c:\program files (x86)\intel\oneapi\
@set onedrive=c:\users\indrekis\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\devinit;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x86;c:\program files (x86)\common files\intel\shared libraries\ia32;c:\program files (x86)\common files\intel\shared libraries\intel64;c:\program files (x86)\common files\intel\shared libraries\;c:\program files (x86)\intel\oneapi\tbb\latest\redist\intel64\vc_mt\;c:\program files (x86)\intel\oneapi\tbb\latest\redist\ia32\vc_mt\;c:\program files (x86)\pc connectivity solution\;c:\program files\microsoft mpi\bin\;c:\program files (x86)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi\intel64\bin;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\ia32_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\ia32_win\mpirt;c:\program files (x86)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files (x86)\winscp\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files (x86)\quicktime\qtsystem\;c:\users\indrekis\.cargo\bin;c:\windows\system32\openssh\;c:\program files\nvidia corporation\nvidia nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\nvidia corporation\nsight compute 2019.5.0\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\the varcem team\varcem\\bin;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files\calibre2\;c:\program files\putty\;c:\program files\miktex\miktex\bin\x64\;c:\program files\dotnet\;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\gs\gs9.56.1\bin;c:\program files\git\cmd;c:\program files\pandoc\;c:\users\indrekis\appdata\local\programs\python\python310\scripts\;c:\users\indrekis\appdata\local\programs\python\python310\;d:\workcomp\msys2_64_2015\mingw64\bin;c:\users\indrekis\.cargo\bin;c:\users\indrekis\appdata\local\microsoft\windowsapps;c:\program files (x86)\atmel\flip 3.4.7\bin;c:\opensourcefiles\radare2;d:\embedded\intelfpga_lite\19.1\modelsim_ase\win32aloem;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\indrekis\appdata\local\programs\ipfs desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\llvm\x64\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\indrekis\appdata\local\microsoft\visualstudio\16.0_e1eaee60\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 158 stepping 9, genuineintel
@set processor_level=6
@set processor_revision=9e09
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_extensionspath_vs2017=c:\program files (x86)\msbuild\
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_extensionspath_vs2022=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files (x86)\microsoft visual studio\2019\community
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pvsbuildtools_installdir_vs2022=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_vctargetspath_current=c:\program files (x86)\microsoft visual studio\2019\community\msbuild\microsoft\vc\v160\
@set pvsbuildtools_visualstudioversion_current=16.0
@set qsys_rootdir=d:\embedded\intelfpga_lite\19.1\quartus\sopc_builder\bin
@set qtjava=c:\program files (x86)\java\jre1.8.0_151\lib\ext\qtjava.zip
@set quartus_rootdir=c:\program files (x86)\intel\oneapi\intelfpgadpcpp\2021.1.1\quartusprimepro\19.4\quartus
@set servicehublogsessionkey=892d306d
@set sessionname=console
@set sopc_kit_nios2=c:\program files (x86)\intel\oneapi\intelfpgadpcpp\2021.1.1\quartusprimepro\19.4\nios2eds
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\indrekis\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\indrekis\appdata\local\temp
@set ucrtversion=10.0.22000.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-21utcdt
@set userdomain_roamingprofile=desktop-21utcdt
@set username=indrekis
@set userprofile=c:\users\indrekis
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.29.30133\
@set vctoolsversion=14.29.30133
@set visualstudiodir=c:\users\indrekis\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio community 2019
@set visualstudioversion=16.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vs2017installdir=c:\program files (x86)\microsoft visual studio\2017\community
@set vs2019installdir=c:\program files (x86)\microsoft visual studio\2019\community
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.11.16
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1033
@set vsskuedition=community
@set vtune_profiler_2020_dir=c:\program files (x86)\intelswtools\vtune profiler 2020\
@set vtune_profiler_2022_dir=c:\program files (x86)\intel\oneapi\vtune\2022.0.0
@set vxipnppath=c:\program files (x86)\ivi foundation\visa\
@set vxipnppath64=c:\program files\ivi foundation\visa\
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files (x86)\windows kits\10\references\10.0.22000.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.22000.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.22000.0\
@set windowssdkversion=10.0.22000.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set zes_enable_sysman=1
@set __devinit_path=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\devinit\devinit.exe
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30133\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x64;c:\program files (x86)\intelswtools\system_studio_2020\opencl\sdk\bin\x86;c:\program files (x86)\common files\intel\shared libraries\ia32;c:\program files (x86)\common files\intel\shared libraries\intel64;c:\program files (x86)\common files\intel\shared libraries\;c:\program files (x86)\intel\oneapi\tbb\latest\redist\intel64\vc_mt\;c:\program files (x86)\intel\oneapi\tbb\latest\redist\ia32\vc_mt\;c:\program files (x86)\pc connectivity solution\;c:\program files\microsoft mpi\bin\;c:\program files (x86)\intelswtools\compilers_and_libraries_2020.4.311\windows\mpi\intel64\bin;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\ia32_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\mpirt;c:\program files (x86)\common files\intel\shared libraries\redist\intel64_win\compiler;c:\program files (x86)\common files\intel\shared libraries\redist\ia32_win\mpirt;c:\program files (x86)\common files\oracle\java\javapath;c:\programdata\oracle\java\javapath;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files (x86)\winscp\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files (x86)\quicktime\qtsystem\;c:\users\indrekis\.cargo\bin;c:\windows\system32\openssh\;c:\program files\nvidia corporation\nvidia nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\nvidia corporation\nsight compute 2019.5.0\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\the varcem team\varcem\\bin;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files\calibre2\;c:\program files\putty\;c:\program files\miktex\miktex\bin\x64\;c:\program files\dotnet\;c:\program files\docker\docker\resources\bin;c:\programdata\dockerdesktop\version-bin;c:\program files\gs\gs9.56.1\bin;c:\program files\git\cmd;c:\program files\pandoc\;c:\users\indrekis\appdata\local\programs\python\python310\scripts\;c:\users\indrekis\appdata\local\programs\python\python310\;d:\workcomp\msys2_64_2015\mingw64\bin;c:\users\indrekis\.cargo\bin;c:\users\indrekis\appdata\local\microsoft\windowsapps;c:\program files (x86)\atmel\flip 3.4.7\bin;c:\opensourcefiles\radare2;d:\embedded\intelfpga_lite\19.1\modelsim_ase\win32aloem;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\indrekis\appdata\local\programs\ipfs desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win
@set __vscmd_script_err_count=0

@call "cl.exe" @"D:\WorkWWW\Blog\ComputersHistory.S\System_soft\tcmp_fdimage_plugin\img_source\StdAfx.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1